IoT/urls.py
from django.conf.urls import url
from django.contrib import admin
from interface.views import home,login,default,pi,logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',home),
    url(r'^login/',login),
    url(r'^logout/',logout),
    url(r'^$',default),
    url(r'^pi',pi)
]

interface/models.py
from django.db import models

# Create your models here.
class Device(models.Model):
    device_id=models.IntegerField(primary_key=True)
    device_status=models.BooleanField(default=False)
    device_name=models.CharField(choices=[
        ('LT','Light'),
        ('FN','Fan')
    ],max_length=20)
    room_number=models.IntegerField(default=0)


    def __str__(self):
        return self.device_name

interface/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .models import Device
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login as auth, logout as lout


# Create your views here.
def default(request):
    print("default")
    if request.user.is_authenticated:
        return redirect("/home")
    return redirect("/login")


def home(request):
    if not request.user.is_authenticated:
        return redirect('/')
    if 'id' in request.GET:
        if (request.GET["id"] != ""):
            print("Hello")
            a = Device.objects.filter(device_id=request.GET['id']).all()
            if a[0].device_status:
                a.update(device_status=False)
            else:
                a.update(device_status=True)
        return redirect("/home")
    devices = Device.objects.all()
    print(devices)
    return render(request, "interface/index.html", {"devices": devices})


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        a = authenticate(username=username, password=password)
        print ("Hello ****\n\n\n\n\n************")

        print(a)
        if a == None:
            return render(request, "interface/authenticate_page.html",
                          {"message": "Please enter a vaild user name and passowrd."})
        auth(request, a)
        return redirect('/')
    return render(request, "interface/authenticate_page.html", {})


def pi(request):
    json = {}
    devices = Device.objects.all()
    for i in devices:
        json[i.device_id] = i.device_status
    return JsonResponse(json)



def logout(request):
    lout(request)
    return redirect('/login')

interface/templates/authenticate_page.html
<!DOCTYPE html>
<html>
	<head>
        {% load static %}
		<title>Home Automation</title>
		<link rel="shortcut icon" href="{% static 'images/home_automation_logo.png'%}" type="image/x-icon">
		<link rel="stylesheet" type="text/css" href="{%static 'interface/css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{%static 'interface/css/style.css'%}">
	</head>
	<body>
		<div class="container">
			<div class="text-center">
				<p class="large theme-color">Login</p>
				<img class="logo" src="{% static 'images/home_automation_logo.png'%}" alt="Home Automation Logo">
			</div>

			<div class="row" >
				<div class="col-md-6 col-md-offset-3">
						<form class="form-horizontal padding-top" action="" method="post">
							{% csrf_token %}
							<div class="form-group">
								<label class="control-label col-sm-2" for="user_name">Username:</label>
								<div class="col-sm-10">
									<input type="text" class="form-control" id="user_name" placeholder="Username" name="username">

								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-sm-2" for="pwd">Password:</label>
								<div class="col-sm-10">
									<input type="password" class="form-control" id="pwd" placeholder="Enter password" name="password">
									<p class='text-danger' id="error-username">{{message}}</p>
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<div class="checkbox">
										<label><input type="checkbox" name="remember"> Remember me</label>
									</div>
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-primary" value="Login">Submit</button>
								</div>
							</div>
						</form>
				</div>
			</div>
			<footer class="row">
				<div class="text-center">
					<p class="small footer-text">Created by Team Sudo for COMP 308<br>Interface design by <a href="#">@unovaxan&@Dvinespark</a><br>Backend by <a href="https://github.com/prashant-subedi/">@prashant-subedi</a></p>
				</div>
			</footer>
			<!--
			<div class="row">
						<div class="col-md-6">

						</div>
						<div class="col-md-6">

						</div>
			</div>
			-->
		</div>
		<script src="js/jquery-3.2.1.min.js">
		</script>
		<script src="js/bootstrap.min.js">
		</script>
	</body>
</html>

interface/templates/interface/authenticate_page.html
<!DOCTYPE html>
<html>
	<head>
        {% load static %}
		<title>Login</title>
		<link rel="shortcut icon" href="{% static 'images/home_automation_logo.png'%}" type="image/x-icon">
		<link rel="stylesheet" type="text/css" href="{%static 'interface/css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{%static 'interface/css/style.css'%}">
	</head>
	<body>
		<div class="container">
			<div class="text-center">
				<p class="large theme-color">Login</p>
				<img class="logo" src="{% static 'images/home_automation_logo.png'%}" alt="Home Automation Logo">
			</div>

			<div class="row" >
				<div class="col-md-6 col-md-offset-3">
						<form class="form-horizontal padding-top" action="" method="post">
							{% csrf_token %}
							<div class="form-group">
								<label class="control-label col-sm-2" for="user_name">Username:</label>
								<div class="col-sm-10">
									<input type="text" class="form-control" id="user_name" placeholder="Username" name="username">

								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-sm-2" for="pwd">Password:</label>
								<div class="col-sm-10">
									<input type="password" class="form-control" id="pwd" placeholder="Enter password" name="password">
									<p class='text-danger' id="error-username">{{message}}</p>
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<div class="checkbox">
										<label><input type="checkbox" name="remember"> Remember me</label>
									</div>
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-primary" value="Login">Submit</button>
								</div>
							</div>
						</form>
				</div>
			</div>
			<footer class="row">
				<div class="text-center">
					<p class="small footer-text">Created by Team Sudo for COMP 308<br>Interface design by <a href="#">@unovaxan&@Dvinespark</a><br>Backend by <a href="https://github.com/prashant-subedi/">@prashant-subedi</a></p>
				</div>
			</footer>
			<!--
			<div class="row">
						<div class="col-md-6">

						</div>
						<div class="col-md-6">

						</div>
			</div>
			-->
		</div>
		<script src="js/jquery-3.2.1.min.js">
		</script>
		<script src="js/bootstrap.min.js">
		</script>
	</body>
</html>

interface/templates/interface/home.html
<html>
<head>
    {%load staticfiles %}

    <title>
        IoT interface
    </title>
    <link rel="stylesheet" href="{% static 'w3.css' %}">

</head>
<body>
<h1>
    <div class="w3-container">
        <div class="w3-blue">List of Devices</div>
        {%for i in devices%}
              <a href="?id={{i.device_id}}"><div class="w3-panel">
                    <div class="w3-topbar w3-leftbar w3-rightbar w3-bottombar">
                        {{i.get_device_name_display}}
                {% if i.device_status%}
                    on
                {%else%} off
                {%endif%}
                    </div>
              </div></a>
                <br>
        {%endfor%}
        <a href="/logout"> Logout </a>
    </div>
</h1>
</body>
</html>

interface/templates/interface/index.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>Home Automation</title>
    <link rel="shortcut icon" href="{% static 'images/home_automation_logo.png'%}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{%static 'interface/css/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'interface/css/style.css'%}">
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
<div class="container">
    <div class="text-center">
        <p class="large theme-color">Login</p>
        <img class="logo" src="{% static 'images/home_automation_logo.png'%}" alt="Home Automation Logo">
    </div>
    <nav class="navbar navbar-light bg-faded">

        <ul class="nav navbar-nav">
             <li class="nav-item active">
                {{user}}
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
        </ul>
        <form id="logout" class="form-inline navbar-form pull-right">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>
            </ul>
        </form>
    </nav>
    <div class="row">
         <h2>Controls</h2>
        <div class="controls col-md-12">
            <p class="small">You can click on the toggle switch to change the status of the corresponding device.</p>
            {%for i in devices%}
              <a href="?id={{i.device_id}}"><div class="w3-panel">
                  <div class="w3-topbar w3-leftbar w3-rightbar w3-bottombar">

                    {% if i.device_status%}
                      <li>
                          <div><input type="hidden" id="living-room-lights" name="living-room-lights" class="switch"/><i
                            class="fa fa-toggle-on fa-2x"></i><label for="living-room-lights"> {{i.get_device_name_display}}</label>
                          </div>
                      </li>
                      {%else%}
                       <li>
                          <div><input type="hidden" id="living-room-lights" name="living-room-lights" class="switch"/><i
                            class="fa fa-toggle-off fa-2x"></i><label for="living-room-lights"> {{i.get_device_name_display}}</label>
                          </div>
                      </li>
                     {%endif%}
                    </div>
              </div></a>
                <br>
            {%endfor%}




        </div>
    </div>
    <footer class="row">
        <div class="text-center">
            <p class="small footer-text">Created by Team Sudo for COMP 308<br>Interface design by <a
                    href="https://www.facebook.com/unovaxan">@unovaxan</a></p>
        </div>
    </footer>
    <!--
    <div class="row">
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-6">

                                    </div>
    </div>
    -->
</div>
<script src="{% static 'interface/js/jquery-3.2.1.min.js'%}">
</script>
<script src="{ static '%interface/js/bootstrap.min.js' %}">
</script>
<script>
    $(document).ready(function () {

        $('#logout').css('display', 'none');
        $('.navbar>ul').append('<li class="nav-tem"><a class="nav-link" href="/logout">Logout</a></li>');
        $(document).on('click', '.fa-toggle-on', function () {
            $(this).removeClass("fa-toggle-on").addClass("fa-toggle-off");
        });
        $(document).on('click', '.fa-toggle-off', function () {
            $(this).removeClass('fa-toggle-off').addClass('fa-toggle-on');
        });
    });
</script>
</body>
</html>